# Generated by Django 5.0.7 on 2024-07-14 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('banner', models.ImageField(upload_to='banners/')),
                ('regras_pontuacao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DesafioAtribuido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_atribuidos_accounts', to=settings.AUTH_USER_MODEL)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.desafio')),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField()),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.desafio')),
            ],
        ),
    ]
