# Generated by Django 5.0.7 on 2024-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafioatribuido',
            name='data_interacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
